before_script:
  - eval $(ssh-agent -s)
  - echo "$ID_RSA" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # - ssh-keyscan $SERVER >> ~/.ssh/known_hosts
  # - chmod 644 ~/.ssh/known_hosts
variables:
  REPO_URL: "registry.gitlab.com/eska-workspace/udemy-progress-monitor"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - build

build:
  image: docker:20.10.16
  stage: build
  services:
  - docker:20.10.16-dind
  script:
    # - echo $IMAGE_TAG
    - ssh -v deployer@$SERVER "hostname && echo 'welcome' > /srv/test"
    # - echo $CI_REGISTRY_USER
    # - echo $CI_REGISTRY_PASSWORD
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker build -t $IMAGE_TAG .
    # - docker push $IMAGE_TAG