variables:
  REPO_URL: "registry.gitlab.com/eska-workspace/udemy-progress-monitor"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - build
  - deploy

build:
  image: docker:20.10.23
  stage: build
  services:
  - docker:20.10.23-dind
  script:
    - echo $IMAGE_TAG
    - echo tag is $CI_COMMIT_REF_SLUG
    # - ssh -v deployer@$SERVER "hostname && echo 'welcome' > /srv/test"
    # - echo $CI_REGISTRY_USER
    # - echo $CI_REGISTRY_PASSWORD
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker build -t $IMAGE_TAG .
    # - docker push $IMAGE_TAG

deploy:
  image: docker:20.10.23
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$ID_RSA" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan "$SERVER" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo tag is $CI_COMMIT_REF_SLUG
    - ssh deployer@$SERVER "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh deployer@$SERVER "/srv/udemy-progress-monitor/reload.sh $CI_COMMIT_REF_SLUG"